src/Entity/Information.php
<?php

namespace App\Entity;

use App\Repository\InformationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=InformationRepository::class)
 */
class Information
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $mail;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $phone_number;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $linkedin;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(string $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getLinkedin(): ?string
    {
        return $this->linkedin;
    }

    public function setLinkedin(string $linkedin): self
    {
        $this->linkedin = $linkedin;

        return $this;
    }
}

src/Form/InformationType.php
<?php

namespace App\Form;

use App\Entity\Information;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class InformationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('mail')
            ->add('adress')
            ->add('phone_number')
            ->add('linkedin')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Information::class,
        ]);
    }
}

src/Controller/InformationController.php
<?php

namespace App\Controller;

use App\Entity\Information;
use App\Form\InformationType;
use App\Repository\InformationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/information")
 */
class InformationController extends AbstractController
{
    /**
     * @Route("/", name="information_index", methods={"GET"})
     */
    public function index(InformationRepository $informationRepository): Response
    {
        return $this->render('information/index.html.twig', [
            'information' => $informationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="information_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $information = new Information();
        $form = $this->createForm(InformationType::class, $information);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($information);
            $entityManager->flush();

            return $this->redirectToRoute('information_index');
        }

        return $this->render('information/new.html.twig', [
            'information' => $information,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="information_show", methods={"GET"})
     */
    public function show(Information $information): Response
    {
        return $this->render('information/show.html.twig', [
            'information' => $information,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="information_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Information $information): Response
    {
        $form = $this->createForm(InformationType::class, $information);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('information_index');
        }

        return $this->render('information/edit.html.twig', [
            'information' => $information,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="information_delete", methods={"POST"})
     */
    public function delete(Request $request, Information $information): Response
    {
        if ($this->isCsrfTokenValid('delete'.$information->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($information);
            $entityManager->flush();
        }

        return $this->redirectToRoute('information_index');
    }
}

templates/information/_delete_form.html.twig
<form method="post" action="{{ path('information_delete', {'id': information.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ information.id) }}">
    <button class="btn">Delete</button>
</form>

templates/information/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/information/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Information{% endblock %}

{% block body %}
    <h1>Edit Information</h1>

    {{ include('information/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('information_index') }}">back to list</a>

    {{ include('information/_delete_form.html.twig') }}
{% endblock %}

templates/information/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Information index{% endblock %}

{% block body %}
    <h1>Information index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Mail</th>
                <th>Adress</th>
                <th>Phone_number</th>
                <th>Linkedin</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for information in information %}
            <tr>
                <td>{{ information.id }}</td>
                <td>{{ information.mail }}</td>
                <td>{{ information.adress }}</td>
                <td>{{ information.phoneNumber }}</td>
                <td>{{ information.linkedin }}</td>
                <td>
                    <a href="{{ path('information_show', {'id': information.id}) }}">show</a>
                    <a href="{{ path('information_edit', {'id': information.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('information_new') }}">Create new</a>
{% endblock %}

templates/information/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Information{% endblock %}

{% block body %}
    <h1>Create new Information</h1>

    {{ include('information/_form.html.twig') }}

    <a href="{{ path('information_index') }}">back to list</a>
{% endblock %}

templates/information/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Information{% endblock %}

{% block body %}
    <h1>Information</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ information.id }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ information.mail }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ information.adress }}</td>
            </tr>
            <tr>
                <th>Phone_number</th>
                <td>{{ information.phoneNumber }}</td>
            </tr>
            <tr>
                <th>Linkedin</th>
                <td>{{ information.linkedin }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('information_index') }}">back to list</a>

    <a href="{{ path('information_edit', {'id': information.id}) }}">edit</a>

    {{ include('information/_delete_form.html.twig') }}
{% endblock %}